POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MDJkMTVjMGMxMzUzZjNhYzBkZDJjOTUiLCJpYXQiOjE2MTM1Njc0MzN9.Cw1zQpZCM5I1uwVLv4bOHvAkj6prHrk2sBy1Yvdl0Oc

{
    "title": "testi",
    "url": "http://www.iltalehti.fi",
    "likes": "10"
}