PUT http://localhost:3003/api/blogs/601a9d394e9fed2480a1a996
Content-Type: application/json

{
    "title": "Jaakko koodaa Full Stackia",
    "author": "Jaakko",
    "url": "https://www.fullstackopen.com",
    "likes": 5
}